### ISSUE TITLE
Bug: dapp crash when back from coinbase wallet app

### ISSUE THREAD

**Issue by hamberluo** [MobileWalletProtocol/wallet-mobile-sdk#243]
### Describe the bug

dapp crash when back from coinbase wallet app

### Steps

1. CoinbaseWalletSDK.shared.configure
2. CoinbaseWalletSDK.shared.initiateHandshake
3. click "allow" to connect dapp
4. crash when return

### Expected behavior

do not crash, like demo

### Version

flutter coinbase wallet 1.0.6, android 1.0.4

### Additional info

```
[        ] E/AndroidRuntime( 9952): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0,  javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
[        ] E/AndroidRuntime( 9952): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5677)
[        ] E/AndroidRuntime( 9952): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5716)
[        ] E/AndroidRuntime( 9952): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
[        ] E/AndroidRuntime( 9952): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
[        ] E/AndroidRuntime( 9952): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[        ] E/AndroidRuntime( 9952): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[        ] E/AndroidRuntime( 9952): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)
[        ] E/AndroidRuntime( 9952): 	at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime( 9952): 	at android.os.Looper.loopOnce(Looper.java:240)
[        ] E/AndroidRuntime( 9952): 	at android.os.Looper.loop(Looper.java:351)
[        ] E/AndroidRuntime( 9952): 	at android.app.ActivityThread.main(ActivityThread.java:8416)
[        ] E/AndroidRuntime( 9952): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 9952): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
[        ] E/AndroidRuntime( 9952): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
[        ] E/AndroidRuntime( 9952): Caused by: javax.crypto.AEADBadTagException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
[        ] E/AndroidRuntime( 9952): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
[        ] E/AndroidRuntime( 9952): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
[        ] E/AndroidRuntime( 9952): 	at com.android.org.conscrypt.OpenSSLAeadCipher.throwAEADBadTagExceptionIfAvailable(OpenSSLAeadCipher.java:320)
[        ] E/AndroidRuntime( 9952): 	at com.android.org.conscrypt.OpenSSLAeadCipher.doFinalInternal(OpenSSLAeadCipher.java:371)
[        ] E/AndroidRuntime( 9952): 	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
[        ] E/AndroidRuntime( 9952): 	at javax.crypto.Cipher.doFinal(Cipher.java:2114)
[        ] E/AndroidRuntime( 9952): 	at com.google.crypto.tink.aead.internal.InsecureNonceAesGcmJce.decrypt(InsecureNonceAesGcmJce.java:142)
[        ] E/AndroidRuntime( 9952): 	at com.google.crypto.tink.subtle.AesGcmJce.decrypt(AesGcmJce.java:63)
[        ] E/AndroidRuntime( 9952): 	at com.coinbase.android.nativesdk.message.Cipher.decrypt(Cipher.kt:16)
[        ] E/AndroidRuntime( 9952): 	at com.coinbase.android.nativesdk.message.response.ResponseSerializer.deserialize(ResponseSerializer.kt:65)
[        ] E/AndroidRuntime( 9952): 	at com.coinbase.android.nativesdk.message.response.ResponseSerializer.deserialize(ResponseSerializer.kt:19)
[        ] E/AndroidRuntime( 9952): 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
[        ] E/AndroidRuntime( 9952): 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
[        ] E/AndroidRuntime( 9952): 	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
[        ] E/AndroidRuntime( 9952): 	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
[        ] E/AndroidRuntime( 9952): 	at com.coinbase.android.nativesdk.message.MessageSerializer.deserialize(Message.kt:60)
[        ] E/AndroidRuntime( 9952): 	at com.coinbase.android.nativesdk.message.MessageSerializer.deserialize(Message.kt:32)
[        ] E/AndroidRuntime( 9952): 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
[        ] E/AndroidRuntime( 9952): 	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
[        ] E/AndroidRuntime( 9952): 	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
[        ] E/AndroidRuntime( 9952): 	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
[        ] E/AndroidRuntime( 9952): 	at com.coinbase.android.nativesdk.message.MessageConverter.decodeResponse(MessageConverter.kt:78)
[        ] E/AndroidRuntime( 9952): 	at com.coinbase.android.nativesdk.CoinbaseWalletSDK.handleResponse(CoinbaseWalletSDK.kt:184)
[        ] E/AndroidRuntime( 9952): 	at com.coinbase.flutter.wallet_sdk.CoinbaseWalletSdkFlutterPlugin.onActivityResult(CoinbaseWalletSdkFlutterPlugin.kt:193)
[        ] E/AndroidRuntime( 9952): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:809)
[        ] E/AndroidRuntime( 9952): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:432)
[        ] E/AndroidRuntime( 9952): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:872)
[        ] E/AndroidRuntime( 9952): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:1221)
[        ] E/AndroidRuntime( 9952): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:691)
[        ] E/AndroidRuntime( 9952): 	at android.app.Activity.dispatchActivityResult(Activity.java:8756)
[        ] E/AndroidRuntime( 9952): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5670)
```

### Smartphone

- Device: OnePlus 11
- Android: 13

**Comment by hamberluo** [comment]
sorry, misuse of resetSession
